config/routes.rb
Tarsier::Application.routes.draw do
  resources :brands, only: [ :index ]
  
  resources :tags, only: [ :index ]

  resources :articles

  devise_for :users
  
  resources :users do
    member do
      get :edit_profile
      put :update_profile
    end
  end
  
  root to: 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include RoleModel
  
  roles :admin, :regular
  
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable
  
  # Scopes
  scope :ordered_list, order('lastname ASC')

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :lastname, :email, :password, :password_confirmation,
    :roles, :remember_me, :lock_version
  
  # Validations
  validates :name, presence: true
  validates :name, :lastname, :email, length: { maximum: 255 }, allow_nil: true,
    allow_blank: true
  
  def to_s
    [self.name, self.lastname].compact.join(' ')
  end
  
  alias_method :old_roles, :roles
  
  def roles
    self.old_roles.map(&:to_sym)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_current_user, only: [:edit_profile, :update_profile]
  
  check_authorization
  load_and_authorize_resource
  
  # GET /users
  # GET /users.json
  def index
    @title = t 'view.users.index_title'
    @users = @users.ordered_list.paginate(
      page: params[:page], per_page: LINES_PER_PAGE
    )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = t 'view.users.show_title'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @title = t 'view.users.new_title'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @title = t 'view.users.edit_title'
  end

  # POST /users
  # POST /users.json
  def create
    @title = t 'view.users.new_title'

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t('view.users.correctly_created') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    authorize! :assign_roles, @user if params[:user] && params[:user][:roles]
    @title = t 'view.users.edit_title'

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: t('view.users.correctly_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    
  rescue ActiveRecord::StaleObjectError
    flash.alert = t 'view.users.stale_object_error'
    redirect_to edit_user_url(@user)
  end
  
  # GET /users/1/edit_profile
  def edit_profile
    @title = t('view.users.edit_profile')
  end
  
  # PUT /users/1/update_profile
  # PUT /users/1/update_profile.xml
  def update_profile
    @title = t('view.users.edit_profile')
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(edit_profile_user_url(@user), notice: t('view.users.profile_correctly_updated')) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit_profile' }
        format.xml  { render xml: @user.errors, status: :unprocessable_entity }
      end
    end

  rescue ActiveRecord::StaleObjectError
    flash.alert = t('view.users.stale_object_error')
    redirect_to edit_profile_user_url(@user)
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def load_current_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_user_roles_options(form)
    options = User.valid_roles.map { |r| [t("view.users.roles.#{r}"), r] }
    
    form.input :roles, collection: options, as: :check_boxes,
      wrapper_html: { class: 'inputs-list' }, label: false
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-stacked' }) do |f| %>
  <div class="inputs">
    <%= f.input :name, input_html: { autofocus: true, maxlength: 255 } %>
    <%= f.input :lastname, input_html: { maxlength: 255 } %>
    <%= f.input :email, required: true, input_html: { maxlength: 255 } %>

    <% if ['new', 'create'].include?(action_name) %>
      <%= f.input :password, required: true, input_html: { maxlength: 255 } %>
      <%= f.input :password_confirmation, input_html: { maxlength: 255 } %>
    <% end %>

    <% if can? :assign_roles, @user %>
      <label><%= User.human_attribute_name 'roles' %></label>
      <%= show_user_roles_options(f) %>
    <% end %>
  </div>
  
  <div class="actions">
    <%= f.input :lock_version, as: :hidden %>
    <%= f.button :submit, class: 'primary' %>
    <div class="secondary-action"><%= yield :form_actions %></div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to t('label.show'), @user %> |
  <%= link_to t('label.list'), users_path %>
<% end %>

<%= render 'form' %>

app/views/users/edit_profile.html.erb
<%= simple_form_for(@user, url: update_profile_user_path(@user), html: { class: 'form-stacked' }) do |f| %>
  <div class="inputs">
    <%= f.input :name, input_html: { autofocus: true, maxlength: 255 } %>
    <%= f.input :lastname, input_html: { maxlength: 255 } %>
    <%= f.input :email, required: true, input_html: { maxlength: 255 } %>
  </div>
  
  <%= f.input :lock_version, as: :hidden %>
  <%= f.button :submit, t('view.users.update_profile'), class: 'primary' %>
<% end %>

<%= simple_form_for(@user, url: update_profile_user_path(@user), html: { class: 'form-stacked', id: "edit_password_#{@user.to_param}" }) do |f| %>
  <div class="inputs">
    <%= f.input :password, required: true, input_html: { maxlength: 255 } %>
    <%= f.input :password_confirmation, input_html: { maxlength: 255 } %>
  </div>

  <%= f.input :lock_version, as: :hidden, input_html: { id: "user_lock_version_password_#{@user.to_param}" } %>
  <%= f.button :submit, t('view.users.update_password') %>
<% end %>

<br />

app/views/users/index.html.erb
<table class="zebra-striped resource-list">
  <thead>
    <tr>
      <th><%= User.human_attribute_name 'name' %></th>
      <th><%= User.human_attribute_name 'lastname' %></th>
      <th><%= User.human_attribute_name 'email' %></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user, title: t('label.show') %></td>
        <td><%= link_to user.lastname, user, title: t('label.show') %></td>
        <td><%= mail_to user.email %></td>
        <td><%= link_to_edit edit_user_path(user) %></td>
        <td><%= link_to_destroy user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagination_links(@users) %>

<nav class="actions">
  <%= link_to t('label.new'), new_user_path, class: 'btn primary' %>
</nav>

app/views/users/new.html.erb
<%= content_for :form_actions do %>
  <%= link_to t('label.list'), users_path %>
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="readonly_data">
  <h2><%= @user %></h2>

  <p>
    <%= mail_to @user.email %>
  </p>

  <% unless @user.roles.empty? %>
    <h3><%= User.human_attribute_name 'roles' %></h3>
    <ul>
      <% @user.roles.each do |role| %>
        <li><%= t("view.users.roles.#{role}") %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<nav class="actions">
  <%= link_to t('label.edit'), edit_user_path(@user), class: 'btn primary' %>
  <div class="secondary-action">
    <%= link_to t('label.list'), users_path %>
  </div>
</nav>